@startwbs
* workflow
** 工作流引擎
*** 1 解析流程定义，生成流程实例、节点实例
*** 2 控制流程实例、流程节点及其各种流转状态
*** 3 控制流程走向，包含提交、退回、作废、会签等
*** 4 流程参与人参与
*** 5 提供接口，用于应用层开发

** 流程管理工具
*** 管理模块
**** 流程角色管理
**** 流程版本管理
**** 流程编码管理
*** 监控模块
**** 跟踪监控流程实例的状态
**** 流程节点的状态
**** 流转的路径

** 流程定义工具
*** 图形化管理工具
**** 定义成一个流程图，最终交由流程引擎解析。
*** 图形化建模
*** 流转条件定义
*** 以关系数据形式或XML文件格式存放定义逻辑

** 业务应用端
@endwbs
